### ISSUE TITLE
Clean up CSS [high priority]

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_toxicity_map#43]
@bowon could you please go through the css/ directory and remove any un-necessary CSS files and code? Seems like we need to keep `legend.css` and `map.css` but I'm assuming there's left over code in `map.css` that was being used for Bootstrap? Could you please go through that file and clean it up?

**Comment by bowon** [comment]
Got it.

Bowon

**Comment by bowon** [comment]
Can you describe me what was happening for this issue or what is on process of change? 

Bowon

**Comment by clhenrick** [comment]
@bowon when do you anticipate having this completed?

**Comment by clhenrick** [comment]
@bowon focus on this issue as well, thanks.

**Comment by bowon** [comment]
Sure. Browser thing was assigned by myself just after submit the beta site at mid August, not recently. 
Related to the CSS, I want to scream to myself at last July. It will done tomorrow night or Thursday : I can’t work in comming Wednesday. 

Bw

**Comment by bowon** [comment]
- [ ] Remove unnecessary setting of CSS 
- [ ] Ordering CSS selectors and elements  
- [ ] implement media query setting

**Comment by bowon** [comment]
- [x] Remove unused selectors from both index.html / CSS
- [x] Remove global CSS selectors  
- [ ] Write media query setting for height setting  
- [ ] implement media query setting 
- [ ] Ordering CSS selectors and elements 
- [ ] Remove unused setting of CSS Selectors
