### ISSUE TITLE
UI to do's [high priority]

### ISSUE THREAD

**Issue by clhenrick** [bowon/demo_toxicity_map#8]
### TO DO:
- [x] make sure left bar is 100% of window height and no larger, any toggled info (about, map layers, etc.) 
- [ ] tabs should scroll inside, 
- [x] disable scroll at entire window.
- [ ] Responsive setting on the navbar  
- [x] navigation `<li>` elements (about, map layers, about the data, etc.) should all have a mouse hover effect

**Comment by clhenrick** [comment]
- [ ] on page load "about the map" text is displayed
- [ ] add "about the data"
- [ ] git rid of vertical horizontal window scrolling
- [ ] make sure left bar is 100% of window height and no larger, any toggled info (about, map layers, etc.) should scroll inside this area, not the entire window.

**Comment by clhenrick** [comment]
@bowon any reason you got rid of the acordian effect for the "about the data"? I thought it worked well.
https://github.com/bowon/demo_july10/blob/master/js/interaction.js#L39-L61

**Comment by bowon** [comment]
Originally, a long scroll bar was discussed for 'about the data' section with client in July. But the actual amount of delivered contents , which delivered after the meeting, overwhelmed the capacity of a long scroll, I put the text at the accordion to handle it. But still Jessie and Korin preferred a long scroll bar. Probably due to the confirm of client.
I kept the accordion part in case it should be returned. 

Bowon

**Comment by clhenrick** [comment]
@bowon thanks for clarifying.

**Comment by bowon** [comment]
@clhenrick I recall the first of the first version of 'about the data' design that uses next button slides the contents in tab to left will try it..

**Comment by clhenrick** [comment]
@bowon the buttons are no longer staying active when the layer is selected, please fix to how it was before.

![screen shot 2015-09-19 at 11 08 07 pm](https://cloud.githubusercontent.com/assets/161748/9979053/6f0e3106-5f23-11e5-93e5-894be208a52e.png)

**Comment by bowon** [comment]
Button feedbacks are back now.  I’m trying to make the button lighter. Will work on it later on since many things to go now.

**Comment by clhenrick** [comment]
Great, thanks @bowon. A quick suggestion in the interest of time; try to address the larger issues one by one without spending too much time on each, or worrying about little details such as the button color. We are past the deadline for this project and time is of the essence, so focus on resolving the remaining UI tasks and make those a priority. Small details / fine tuning can always be taken care of after the larger UI issues are finished.

**Comment by bowon** [comment]
Agree.

**Comment by clhenrick** [comment]
@bowon in [map.css lines 35 - 81](https://github.com/bowon/demo_july10/blob/master/css/map.css#L35-L81) need to be more descriptive. They are being applied to every element which shouldn't be happening. Be careful when you set CSS for elements globally like `div`, `li`, `div p`, etc. because they will affect every instance in the webpage.

**Comment by clhenrick** [comment]
all of the UI interactions are not yet resolved, please do not close this issue @bowon

**Comment by bowon** [comment]
Of course I won’t.

**Comment by bowon** [comment]
@clhenrick related to the map.css lines 35-81, Agreed. I'm working on it.

**Comment by clhenrick** [comment]
@bowon please hold off and don't commit anything else for now. If you want to continue to work then create a new branch (other than master) and work on that.

**Comment by bowon** [comment]
My apology for this branch issue.  I had to push the commits to change my branch from master to other branch. 
I’m currently at tabsnmss. So you should be fine now.

**Comment by clhenrick** [comment]
do a Git pull and use the code I've written for index.html and interactions.js; no offense but it's a more efficient / less complex fix to what you did in [cd80507](https://github.com/bowon/demo_july10/commit/cd80507493abe5f8965d310b48ef5615a596fff9).

**Comment by bowon** [comment]
Cool. I like what you did here. will continue on the other part.

**Comment by bowon** [comment]
= Make sure the UI look same in each browser environment. Since I’m working on .css() setting at interaction.js, it merges to other to do list.

**Comment by clhenrick** [comment]
@bowon that is not the way to solve browser compatibility. Leave that until the end when the website is functional and all other major issues are resolved.

**Comment by bowon** [comment]
I thought it is assigning css setting depends on the detected browser at jQeury…
I’ll work on metadata section (+ .tabs size control issue) now accordingly.

**Comment by clhenrick** [comment]
Using jQuery to change styles depending on browser detection should be
avoided. It's impossible to get everything looking pixel perfect and
exactly the same across all web browsers, at least in the time we have to
complete this project.


-Chris L Henrick
-------------------------
MFA, Design & Technology
Parsons, The New School For Design

http://chrishenrick.com
*Github:* @clhenrick <https://github.com/clhenrick> *Twitter:*
@chrislhenrick <https://twitter.com/chrislhenrick>

“Whenever I see an adult on a bicycle, I no longer despair for the future
of the human race.”
— H.G. Wells

**Comment by clhenrick** [comment]
@bowon just focus on the UI issues for now.

**Comment by bowon** [comment]
Got it.
